default: &default
  adapter: postgresql

development:
  <<: *default
  database: sidekiq_batches_development

test:
  <<: *default
  database: sidekiq_batches_test

production:
  <<: *default
  database: sidekiq_batches_production
